// GENERATED by scripts/generate-bible-index.mjs — do not edit by hand.
export interface BookInfo { name: string; slug: string; file: string; chapters: number; start: number }
export const BOOKS: BookInfo[] = [
  {
    "name": "Genesis",
    "slug": "genesis",
    "file": "Genesis.json",
    "chapters": 50,
    "start": 0
  },
  {
    "name": "Exodus",
    "slug": "exodus",
    "file": "Exodus.json",
    "chapters": 40,
    "start": 50
  },
  {
    "name": "Leviticus",
    "slug": "leviticus",
    "file": "Leviticus.json",
    "chapters": 27,
    "start": 90
  },
  {
    "name": "Numbers",
    "slug": "numbers",
    "file": "Numbers.json",
    "chapters": 36,
    "start": 117
  },
  {
    "name": "Deuteronomy",
    "slug": "deuteronomy",
    "file": "Deuteronomy.json",
    "chapters": 34,
    "start": 153
  },
  {
    "name": "Joshua",
    "slug": "joshua",
    "file": "Joshua.json",
    "chapters": 24,
    "start": 187
  },
  {
    "name": "Judges",
    "slug": "judges",
    "file": "Judges.json",
    "chapters": 21,
    "start": 211
  },
  {
    "name": "Ruth",
    "slug": "ruth",
    "file": "Ruth.json",
    "chapters": 4,
    "start": 232
  },
  {
    "name": "1 Samuel",
    "slug": "1-samuel",
    "file": "1Samuel.json",
    "chapters": 31,
    "start": 236
  },
  {
    "name": "2 Samuel",
    "slug": "2-samuel",
    "file": "2Samuel.json",
    "chapters": 24,
    "start": 267
  },
  {
    "name": "1 Kings",
    "slug": "1-kings",
    "file": "1Kings.json",
    "chapters": 22,
    "start": 291
  },
  {
    "name": "2 Kings",
    "slug": "2-kings",
    "file": "2Kings.json",
    "chapters": 25,
    "start": 313
  },
  {
    "name": "1 Chronicles",
    "slug": "1-chronicles",
    "file": "1Chronicles.json",
    "chapters": 29,
    "start": 338
  },
  {
    "name": "2 Chronicles",
    "slug": "2-chronicles",
    "file": "2Chronicles.json",
    "chapters": 36,
    "start": 367
  },
  {
    "name": "Ezra",
    "slug": "ezra",
    "file": "Ezra.json",
    "chapters": 10,
    "start": 403
  },
  {
    "name": "Nehemiah",
    "slug": "nehemiah",
    "file": "Nehemiah.json",
    "chapters": 13,
    "start": 413
  },
  {
    "name": "Esther",
    "slug": "esther",
    "file": "Esther.json",
    "chapters": 10,
    "start": 426
  },
  {
    "name": "Job",
    "slug": "job",
    "file": "Job.json",
    "chapters": 42,
    "start": 436
  },
  {
    "name": "Psalms",
    "slug": "psalms",
    "file": "Psalm.json",
    "chapters": 150,
    "start": 478
  },
  {
    "name": "Proverbs",
    "slug": "proverbs",
    "file": "Proverbs.json",
    "chapters": 31,
    "start": 628
  },
  {
    "name": "Ecclesiastes",
    "slug": "ecclesiastes",
    "file": "Ecclesiastes.json",
    "chapters": 12,
    "start": 659
  },
  {
    "name": "Song of Solomon",
    "slug": "song-of-solomon",
    "file": "SongOfSolomon.json",
    "chapters": 8,
    "start": 671
  },
  {
    "name": "Isaiah",
    "slug": "isaiah",
    "file": "Isaiah.json",
    "chapters": 66,
    "start": 679
  },
  {
    "name": "Jeremiah",
    "slug": "jeremiah",
    "file": "Jeremiah.json",
    "chapters": 52,
    "start": 745
  },
  {
    "name": "Lamentations",
    "slug": "lamentations",
    "file": "Lamentations.json",
    "chapters": 5,
    "start": 797
  },
  {
    "name": "Ezekiel",
    "slug": "ezekiel",
    "file": "Ezekiel.json",
    "chapters": 48,
    "start": 802
  },
  {
    "name": "Daniel",
    "slug": "daniel",
    "file": "Daniel.json",
    "chapters": 12,
    "start": 850
  },
  {
    "name": "Hosea",
    "slug": "hosea",
    "file": "Hosea.json",
    "chapters": 14,
    "start": 862
  },
  {
    "name": "Joel",
    "slug": "joel",
    "file": "Joel.json",
    "chapters": 3,
    "start": 876
  },
  {
    "name": "Amos",
    "slug": "amos",
    "file": "Amos.json",
    "chapters": 9,
    "start": 879
  },
  {
    "name": "Obadiah",
    "slug": "obadiah",
    "file": "Obadiah.json",
    "chapters": 1,
    "start": 888
  },
  {
    "name": "Jonah",
    "slug": "jonah",
    "file": "Jonah.json",
    "chapters": 4,
    "start": 889
  },
  {
    "name": "Micah",
    "slug": "micah",
    "file": "Micah.json",
    "chapters": 7,
    "start": 893
  },
  {
    "name": "Nahum",
    "slug": "nahum",
    "file": "Nahum.json",
    "chapters": 3,
    "start": 900
  },
  {
    "name": "Habakkuk",
    "slug": "habakkuk",
    "file": "Habakkuk.json",
    "chapters": 3,
    "start": 903
  },
  {
    "name": "Zephaniah",
    "slug": "zephaniah",
    "file": "Zephaniah.json",
    "chapters": 3,
    "start": 906
  },
  {
    "name": "Haggai",
    "slug": "haggai",
    "file": "Haggai.json",
    "chapters": 2,
    "start": 909
  },
  {
    "name": "Zechariah",
    "slug": "zechariah",
    "file": "Zechariah.json",
    "chapters": 14,
    "start": 911
  },
  {
    "name": "Malachi",
    "slug": "malachi",
    "file": "Malachi.json",
    "chapters": 4,
    "start": 925
  },
  {
    "name": "Matthew",
    "slug": "matthew",
    "file": "Matthew.json",
    "chapters": 28,
    "start": 929
  },
  {
    "name": "Mark",
    "slug": "mark",
    "file": "Mark.json",
    "chapters": 16,
    "start": 957
  },
  {
    "name": "Luke",
    "slug": "luke",
    "file": "Luke.json",
    "chapters": 24,
    "start": 973
  },
  {
    "name": "John",
    "slug": "john",
    "file": "John.json",
    "chapters": 21,
    "start": 997
  },
  {
    "name": "Acts",
    "slug": "acts",
    "file": "Acts.json",
    "chapters": 28,
    "start": 1018
  },
  {
    "name": "Romans",
    "slug": "romans",
    "file": "Romans.json",
    "chapters": 16,
    "start": 1046
  },
  {
    "name": "1 Corinthians",
    "slug": "1-corinthians",
    "file": "1Corinthians.json",
    "chapters": 16,
    "start": 1062
  },
  {
    "name": "2 Corinthians",
    "slug": "2-corinthians",
    "file": "2Corinthians.json",
    "chapters": 13,
    "start": 1078
  },
  {
    "name": "Galatians",
    "slug": "galatians",
    "file": "Galatians.json",
    "chapters": 6,
    "start": 1091
  },
  {
    "name": "Ephesians",
    "slug": "ephesians",
    "file": "Ephesians.json",
    "chapters": 6,
    "start": 1097
  },
  {
    "name": "Philippians",
    "slug": "philippians",
    "file": "Philippians.json",
    "chapters": 4,
    "start": 1103
  },
  {
    "name": "Colossians",
    "slug": "colossians",
    "file": "Colossians.json",
    "chapters": 4,
    "start": 1107
  },
  {
    "name": "1 Thessalonians",
    "slug": "1-thessalonians",
    "file": "1Thessalonians.json",
    "chapters": 5,
    "start": 1111
  },
  {
    "name": "2 Thessalonians",
    "slug": "2-thessalonians",
    "file": "2Thessalonians.json",
    "chapters": 3,
    "start": 1116
  },
  {
    "name": "1 Timothy",
    "slug": "1-timothy",
    "file": "1Timothy.json",
    "chapters": 6,
    "start": 1119
  },
  {
    "name": "2 Timothy",
    "slug": "2-timothy",
    "file": "2Timothy.json",
    "chapters": 4,
    "start": 1125
  },
  {
    "name": "Titus",
    "slug": "titus",
    "file": "Titus.json",
    "chapters": 3,
    "start": 1129
  },
  {
    "name": "Philemon",
    "slug": "philemon",
    "file": "Philemon.json",
    "chapters": 1,
    "start": 1132
  },
  {
    "name": "Hebrews",
    "slug": "hebrews",
    "file": "Hebrews.json",
    "chapters": 13,
    "start": 1133
  },
  {
    "name": "James",
    "slug": "james",
    "file": "James.json",
    "chapters": 5,
    "start": 1146
  },
  {
    "name": "1 Peter",
    "slug": "1-peter",
    "file": "1Peter.json",
    "chapters": 5,
    "start": 1151
  },
  {
    "name": "2 Peter",
    "slug": "2-peter",
    "file": "2Peter.json",
    "chapters": 3,
    "start": 1156
  },
  {
    "name": "1 John",
    "slug": "1-john",
    "file": "1John.json",
    "chapters": 5,
    "start": 1159
  },
  {
    "name": "2 John",
    "slug": "2-john",
    "file": "2John.json",
    "chapters": 1,
    "start": 1164
  },
  {
    "name": "3 John",
    "slug": "3-john",
    "file": "3John.json",
    "chapters": 1,
    "start": 1165
  },
  {
    "name": "Jude",
    "slug": "jude",
    "file": "Jude.json",
    "chapters": 1,
    "start": 1166
  },
  {
    "name": "Revelation",
    "slug": "revelation",
    "file": "Revelation.json",
    "chapters": 22,
    "start": 1167
  }
]
export const TOTAL_CHAPTERS = 1189
