import Foundation

/// Provides the ESV's section headings, and the superscription a psalm carries
/// above its first verse.
///
/// Neither is in the scripture data — the verse-by-verse text carries no
/// editorial structure — so both come from an index generated by
/// `Scripts/generate_headings.py`.
struct HeadingService {
    static let shared = HeadingService()

    struct Heading: Codable {
        let verse: Int
        let text: String
    }

    private struct ChapterHeadings: Codable {
        let headings: [Heading]
        let title: String?
    }

    // book → chapter-string → headings and superscription
    private let data: [String: [String: ChapterHeadings]]

    private init() {
        guard let url = Bundle.main.url(forResource: "headings", withExtension: "json"),
              let jsonData = try? Data(contentsOf: url),
              let raw = try? JSONDecoder().decode([String: [String: ChapterHeadings]].self, from: jsonData) else {
            data = [:]
            return
        }
        data = raw
    }

    /// Section headings for this chapter, each naming the verse it sits above.
    func headings(book: String, chapter: Int) -> [Heading] {
        data[book]?[String(chapter)]?.headings ?? []
    }

    /// A psalm's superscription, printed above verse 1. Nil everywhere else.
    func psalmTitle(book: String, chapter: Int) -> String? {
        data[book]?[String(chapter)]?.title
    }
}
