import Foundation

/// Provides the verses that open a paragraph, taken from the ESV's own layout.
///
/// The scripture data is stored verse by verse and carries no paragraph
/// information, so this comes from a separate index generated by
/// `Scripts/generate_paragraph_starts.py`.
struct ParagraphService {
    static let shared = ParagraphService()

    // book → chapter-string → [verse numbers that open a paragraph]
    private let data: [String: [String: [Int]]]

    private init() {
        guard let url = Bundle.main.url(forResource: "paragraph_starts", withExtension: "json"),
              let jsonData = try? Data(contentsOf: url),
              let raw = try? JSONDecoder().decode([String: [String: [Int]]].self, from: jsonData) else {
            data = [:]
            return
        }
        data = raw
    }

    /// Verse numbers that begin a paragraph in this chapter. Empty when the
    /// index has no entry, which leaves the chapter as one unbroken block.
    func paragraphStarts(book: String, chapter: Int) -> [Int] {
        data[book]?[String(chapter)] ?? []
    }
}
